sudo: required # Any time you use docker you need superuser permissions
services:
    - docker # Need docker CLI. Travis-CI installs a docker CLI in the container

before_install:
    - docker build -t narainmg/git-docker-react-frontend -f Dockerfile.dev .

script:
    - docker run narainmg/git-docker-react-frontend npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "git-docker-react-frontend"
    env: "GitDockerReactFrontend-env"
    bucket_name: "elasticbeanstalk-us-west-2-923770981229"
    bucket_path: "git-docker-react-frontend"

    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

