version: '3'
services:
    web:
        build:
            # Where do we want the files and folders to be pulled from relative 
            # to the directory in which docker-compose is being run
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "9191:3000"
        volumes:
            - /var/app/node_modules
            - .:/var/app

    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /var/app/node_modules
            - .:/var/app
        command: ["npm", "run", "test"]

